#
# ChatMaster Configuration File 
# Version 1.2
# Author: TechMastary
#

#Data is collected from your server anonymously to mcstats.org.
#If you do not wish information to be sent, please set metrics to false.

metrics: true

#Updating the plugin when there is a version.
#(Done manually, type /cmupdate to update)

update: true

#Custom join and leave messages

joinmessage:
    enable: true
    message: &e%player% joined the game.
leavemessage:
    enable: true
    message: &e%player% left the game.